print("je komt thuis na een lange dag werken, je kinderen zijn al aan het slapen en je vrouw heeft eten voor je gekookt.")
print("je zit thuis in je huis kamer en je krijgt een bericht op je telefoon, op dat berricht staat dat je bedreigd word door een groep die je niet kent in het bericht staat dat je gevaar loopt als je buiten je loop je gevaar")
print("je kan kiezen negeer het bericht of ga je het beantwoorden.")
print("antwoord met negeren of beantwoorden")

keuze = input()

if keuze == 'negeren': 

    print("je negeerd het bericht en je gaat verder met waar je mee bezig was")
    print("je krijgt na een uur nog een bericht van de zelfde afzender. ")
    print("het is een anoniem nummer dus je kan zie niet bellen. ze bedreigen je weer dat je moet stoppen om voor de overheid te werken.")
    print("zet je je telefoon uit of laat je hem aan")
    print("antwoord met uitzetten of aanlaten.")

    keuze1 = input()

    if keuze1 == 'aanlaten':
        print("je laat je telefoon aan.")
        print("je krijgt meer berichten van het anonieme nummer.")
        print("je krijgt een bericht dat als je nu niet stopt met werken voor de overheid dat je word vermoord")
        print("je word zo erg bedreigd dat je van plan bent om te vluchten.")
        print("je beld een goede vriend van je of je bij hem even kan verblijven.")
        print("hij neemt op en je verteld wat er is gebeurd en hij begrijpt het en je mag van hem overnachten in zijn huis.")
        print("je verblijft nu al een week bij de vriend. je krijgt weer een bericht van het anonieme nummer.")
        print("ze weten dat je overnacht bij de vriend van je in de hoofdstad van Afganistan.")
        print("je kiest er voor om weer te vluchten, je twijveld om naar een anderland te vluchen of in Afganistan blijven")
        print("antwoord met vluchten of blijven.")

        keuze10 = input()

        if keuze10 == 'blijven':
            print("je heb er voor gekozen om te blijven in Afganistan.")
            print("je zoekt een verblijf in Afganistan")
            print("je heb een hotel gevonden waar je een week kan verblijven")
            print("je heb een hotel kunnen boeken waar je een week kan blijven.")
            print("de week dat je in het hotel verblijft krijg je steeds doods bedreigingen van het anonieme nummer")
            print("na de week moet je ergens anders onderdak zoeken.")
            print("na de week kom je je hotel uitgelopen")
            print("je word voor het hotel opgewacht en word onvoert door een groep mannen")
            print("er word een zak over je hoofd gedaan en je word in een bus gestopt")
            print("je zit voor je gevoel al 4 uur in het busje en je heb geen idee waar je bent of waar je heen gaat")
            print("na 4,5 uur rijden stopt de bus en word je de bus uitgetrokken")
            print("je word op je knieeën gezet en er word tegen je gezegt dat eerder moest stoppen met werken voor de overheid of je moest vluchten")
            print("je word hier om het leven gebracht")
            print("dit is het einde van je leven")
            print("dankjewel voor het spelen van mijn spel")
            antwoord = input()
                        
        elif keuze10 == 'vluchten':
            print("je kiest er voor om te vluchten")
            print("waar ga je heen?")
            print("je kijkt of je naar familie/vrienden in iran kan gaan")
            print("je beld je achter oom en vraagt of hij nog een plekje over heb om te overnachten")
            print("je oom verteld dat je wel een paar nachten kan blijven")
            print("je bent bij je oom en kijkt op je telefoon")
            print("je krijgt een bericht van het anonieme nummer")
            print("er staat in dat je beter moet verstoppen met de locatie van het huis waar je verblijft")
            print("je kan er nu voor kiezen om te blijven of verder te vluchten")
            print("antwoord met blijven of vluchten")
            
            keuze11 = input()

            if keuze11 =='vluchten':
                print("je kiest er voor om te vluchten")
                print("Je wilt vluchten anar Europa")
                print("een vriend van jou kent een smokkelaar die je mee kan nemen naar Europa.")
                print("hij vraagt 10 000 euro om je te helpen naar Engeland.")
                print("je betaald de smokkelaar 10 000 euro om je mee te nemen naar Engeland.")
                print("je komt in contact met de smokkelaar en spreekt af in Iran")
                print("hij komt je ophalen met een zwart busje met geblindeerde ramen")
                print("je moet al je contact middelen inlever zoals je telefoon")
                print("de smokkelaar neemt ook je horloge af")
                print("elke tussen stop is niet te achterhalen waar je bent")
                print("door de geblindeerde ramen heb je geen idee waar je  bent en hoelaat het is")
                print("er is een tussen stop in Turkijë bij de vliegveld van Istanbull.")
                print("bij de vliegveld van Istanbull stappen er 2 andere vluchtenlingen in die ook naar Europa gaan")
                print("je bent al 2 maanden onderweg naar Engeland")
                print("je komt aan in een stad. je heb geen idee waar je bent of hoelaat het is.")
                print("de smokkelaar zegt dat hij wat eten haald voor jullie en dat ze even de benen kunnen strekken")
                print("je wacht al een uur en de smokkelaar is nog niet terug, je vraagd aan de mensen op straat waar je bent.")
                print("iemand verteld dat je in Amsterdam bent.")
                print("je staat om de hoek van het politie bureau")
                print("je gaat naar de politie en verteld je verhaal")
                print("de agent met wie je heb gepraat gaat je helpen")
                print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                print("je kan nu gaan kiezen of je in Nederland wilt blijven?")
                print("antwoord met blijven of anderland")

                keuze12 = input()
                if keuze12 =='anderland':
                    print("je reist naar Duitsland en kijkt of je daar een nieuw leven kan opbouwe.")
                    print("je komt aan in Duitsland en wilt je zelf inburgeren ")
                    print("je bent geslaagd voor je inburgering en mag in Duitsland blijven")
                    print("je soliciteerd bij een taxi bedrijf.")
                    print("je wilt dat je vrouw en kinderen ook naar Nederland komt en vraagt of dat mogelijk is")
                    print("er word geregeld dat je vrouw en kinderen naar Nederland worden gehaald")
                    print("je vrouw haald ook de inburgering en begint ook met werken in Duitsland")
                    print("je kinderen gaan hier naar school en hebben weer een toekomst")
                    print("het was een zware en lange reis maar je heb het gehaald, je bent veilig in Duitsland met je vrouw en kinderen")
                    print("dankjewel voor het spelen van mijn spel je heb het gehaald.")
                    antwoord1 = input()
                    
                elif keuze12 == 'blijven':
                    print("je blijft in nederland en doet een inburgerings toets")
                    print("je bent geslaagd voor je inburgering en mag in nederland blijven")
                    print("je soliciteerd bij een taxi bedrijf.")
                    print("je wilt dat je vrouw en kinderen ook naar Nederland komt en vraagt of dat mogelijk is")
                    print("er word geregeld dat je vrouw en kinderen naar Nederland worden gehaald")
                    print("je vrouw haald ook de inburgering en begint ook met werken in Nederland")
                    print("je kinderen gaan hier naar school en hebben weer een toekomst")
                    print("het was een zware en lange reis maar je heb het gehaald, je bent veilig in Nederland met je vrouw en kinderen")
                    print("dankjewel voor het spelen van mijn spel je heb het gehaald.")
                    antwoord3 = input()                  

            elif keuze11 == 'blijven':
                print("je kiest er voor om te blijven")
                print("je bent de hond van je oom aan het uitlaten buiten")
                print("op dat moment krijg je een bericht met een foto dat je de hond uitlaat")
                print("je kijkt om je heen en ziet niemand")
                print("je loopt al een tijdje en komt een groep met mannen tegen")
                print("je ziet dat ze je aanstaren, maar jij probeert ze te negeren")
                print("je loopt ze voorbij en ziet dat ze achter je aan lopen")
                print("je kijkt achter je en ziet dat ze snel achter je aan lopen")
                print("je begint zelf snel te lopen en je ziet dat hun ook snel beginnen te lopen")
                print("je begint te rennen")
                print("je struikeld over de riem van de hond en valt op de grond")
                print("je wilt opstaan maar je word weer op de grond geduwt door 1 van de mannen")
                print("je blijf liggen en vraagt wat is er, iemand antwoord je had moeten stoppen met voor de overheid werken")
                print("er word een zak over je hoofd gedaan en je word in een bus gestopt")
                print("je zit voor je gevoel al 4 uur in het busje en je heb geen idee waar je bent of waar je heen gaat")
                print("na 4,5 uur rijden stopt de bus en word je de bus uitgetrokken")
                print("je word op je knieeën gezet en er word tegen je gezegt dat eerder moest stoppen met werken voor de overheid of je moest vluchten")
                print("je word hier om het leven gebracht")
                print("dit is het einde van je leven")
                print("dankjewel voor het spelen van mijn spel")
                antwoord4 = input()            

    elif keuze1 == 'uitzetten':

        print("je heb je telefoon uitgezet en je negeerd de berichten die je krijgt")
        print("een dag later")
        print("je zet de volgende dag je telefoon weer aan en krijgt heel veel berichten van het anoniem nummer.")
        print("je krijgt een bericht dat als je nu niet stopt met werken voor de overheid dat je word vermoord")
        print("je word zo erg bedreigd dat je van plan bent om te vluchten.")
        print("je beld een goede vriend van je of je bij hem even kan verblijven.")
        print("hij neemt op en je verteld wat er is gebeurd en hij begrijpt het en je mag van hem overnachten in zijn huis.")
        print("je verblijft nu al een week bij de vriend. je krijgt weer een bericht van het anonieme nummer.")
        print("ze weten dat je overnacht bij de vriend van je in de hoofdstad van Afganistan.")
        print("je kiest er voor om weer te vluchten, je twijveld om naar een anderland te vluchen of in Afganistan blijven")
        print("antwoord met vluchten of blijven.")

        keuze2 = input()
        
        if keuze2 == 'blijven':
            print("je kiest er voor om te blijven")
            print("je bent een rondje buiten aan het lopen")
            print("op dat moment krijg je een bericht met een foto dat je buiten aan het lopen bent")
            print("je kijkt om je heen en ziet niemand")
            print("je loopt al een tijdje en komt een groep met mannen tegen")
            print("je ziet dat ze je aanstaren, maar jij probeert ze te negeren")
            print("je loopt ze voorbij en ziet dat ze achter je aan lopen")
            print("je kijkt achter je en ziet dat ze snel achter je aan lopen")
            print("je begint zelf snel te lopen en je ziet dat hun ook snel beginnen te lopen")
            print("je begint te rennen")
            print("je struikeld en valt op de grond")
            print("je wilt opstaan maar je word weer op de grond geduwt door 1 van de mannen")
            print("je blijf liggen en vraagt wat is er, iemand antwoord je had moeten stoppen met voor de overheid werken")
            print("er word een zak over je hoofd gedaan en je word in een bus gestopt")
            print("je zit voor je gevoel al 4 uur in het busje en je heb geen idee waar je bent of waar je heen gaat")
            print("na 4,5 uur rijden stopt de bus en word je de bus uitgetrokken")
            print("je word op je knieeën gezet en er word tegen je gezegt dat eerder moest stoppen met werken voor de overheid of je moest vluchten")
            print("je word hier om het leven gebracht")
            print("dit is het einde van je leven")
            print("dankjewel voor het spelen van mijn spel")
            antwoord6 = input()    

        elif keuze2 == 'vluchten':

            print("je kiest er voor om te vluchten")
            print("waar ga je heen blijf je in Afganistan of vlucht je naar een ander land?")
            print("antwoord met blijven of vluchten")
                        
            keuze3 = input()

            if keuze3 == 'blijven':
                print("je kiest er voor om te blijven")
                print("je bent een rondje buiten aan het lopen")
                print("op dat moment krijg je een bericht met een foto dat je buiten aan het lopen bent")
                print("je kijkt om je heen en ziet niemand")
                print("je loopt al een tijdje en komt een groep met mannen tegen")
                print("je ziet dat ze je aanstaren, maar jij probeert ze te negeren")
                print("je loopt ze voorbij en ziet dat ze achter je aan lopen")
                print("je kijkt achter je en ziet dat ze snel achter je aan lopen")
                print("je begint zelf snel te lopen en je ziet dat hun ook snel beginnen te lopen")
                print("je begint te rennen")
                print("je struikeld en valt op de grond")
                print("je wilt opstaan maar je word weer op de grond geduwt door 1 van de mannen")
                print("je blijf liggen en vraagt wat is er, iemand antwoord je had moeten stoppen met voor de overheid werken")
                print("er word een zak over je hoofd gedaan en je word in een bus gestopt")
                print("je zit voor je gevoel al 4 uur in het busje en je heb geen idee waar je bent of waar je heen gaat")
                print("na 4,5 uur rijden stopt de bus en word je de bus uitgetrokken")
                print("je word op je knieeën gezet en er word tegen je gezegt dat eerder moest stoppen met werken voor de overheid of je moest vluchten")
                print("je word hier om het leven gebracht")
                print("dit is het einde van je leven")
                print("dankjewel voor het spelen van mijn spel")
                antwoord7 = input()

            elif keuze3 == 'vluchten':
                print("je vlucht naar een ander land maar naar welk land ga je?")
                print("je kan kiezen tussen de buur landen of naar een ver land.")
                print("antwoord met buurlanden of verland")
                
                keuze4 = input()
                if keuze4 == 'verland':
                    print("je wilt vluchten naar een ver land")
                    print("je beld een vriend van je en hij verteld dat hij een smokkelaar kent die je naar Engeland brengt")
                    print("je betaald de smokkelaar 10 000 euro om je mee te nemen naar Engeland.")
                    print("je komt in contact met de smokkelaar en spreekt af in Iran")
                    print("hij komt je ophalen met een zwart busje met geblindeerde ramen")
                    print("je moet al je contact middelen inlever zoals je telefoon")
                    print("de smokkelaar neemt ook je horloge af")
                    print("elke tussen stop is niet te achterhalen waar je bent")
                    print("door de geblindeerde ramen heb je geen idee waar je  bent en hoelaat het is")
                    print("er is een tussen stop in Turkijë bij de vliegveld van Istanbull.")
                    print("bij de vliegveld van Istanbull stappen er 2 andere vluchtenlingen in die ook naar Europa gaan")
                    print("je bent al 2 maanden onderweg naar Engeland")
                    print("je komt aan in een stad. je heb geen idee waar je bent of hoelaat het is.")
                    print("de smokkelaar zecht dat hij wat eten haald voor jullie en dat ze even de benen kunnen strekken")
                    print("je wacht al een uur en de smokkelaar is nog niet terug, je vraagd aan de mensen op straat waar je bent.")
                    print("iemand verteld dat je in Amsterdam bent.")
                    print("je staat om de hoek van het politie bureau")
                    print("je gaat naar de politie en verteld je verhaal")
                    print("de agent met wie je heb gepraat gaat je helpen")
                    print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                    print("je kan nu gaan kiezen of je in Nederland wilt blijven?")
                    print("antwoord met blijven of anderland")

                    keuze13 = input()
                                
                    if keuze13 == 'blijven':
                        print("je blijft in Nederland en haalt je inburgering en je krijgt een uitkering en je kan werk gaan zoeken.")
                        print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar nederland krijgen")
                        print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar nederland")
                        print("je vrouw haalt ook de inburgering en gaat ook werken")
                        print("je kinderene gaan hier naar school")
                        print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                        print("dankje wel voor het spelen van mijn spel")
                        antwoord8 = input()

                    elif keuze13 == 'anderland':
                        print("je kiest er voor om naar een ander land te gaan") 
                        print("naar welk land wil je gaan: België of Duitsland")
                        print("antwoord met België of Duitsland")

                        keuze14 = input()

                        if keuze14 == 'Duitsland':
                            print("je gaat naar Duitsland en komt aan in Berlijn")
                            print("je gaat naar een politie bureau en vraagt of iemand je kan helpen")
                            print("de agent met wie je heb gepraat gaat je helpen")
                            print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                            print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar Duitsland krijgen")
                            print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar Duitsland")
                            print("je vrouw haalt ook de inburgering en gaat ook werken")
                            print("je kinderen gaan hier naar school")
                            print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                            print("dankje wel voor het spelen van mijn spel")
                            antwoord9 = input()

                        elif keuze14 == 'België':
                            print("je gaat naar belgie en komt aan in antwerpen")
                            print("je gaat naar een politie bureau en vraagt of iemand je kan helpen")
                            print("de agent met wie je heb gepraat gaat je helpen")
                            print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                            print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar België krijgen")
                            print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar België")
                            print("je vrouw haalt ook de inburgering en gaat ook werken")
                            print("je kinderen gaan hier naar school")
                            print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                            print("dankje wel voor het spelen van mijn spel")
                            antwoord10 = input()


                elif keuze4 == 'buurland':
                    print("Je hebt gekozen om te vluchten naar een buurland, naar welk land ga")
                    print("Iran of Turkmenistan? ")
                    print("antwoord met Iran of Turkmanistan.")

                    keuze5 = input()

                    if keuze5 == 'Turkmanistan':
                        print("je heb gekozen voor Tukmenistan")
                        print("je heb een hotel gevonden waar je kan overnachten")
                        print("je heb een taxi gebeld en gevraagd of die je naar je hotel kan brengen")
                        print("nadat je in je hotel bent aangekomen gooi je je spullen op de grond en ga je in bed liggen en gaat slapen")
                        print("je word wakker en je telefoon staat vol met berichten van het anonieme nummer")
                        print("ze sturen foto's van je die licht te slapen")
                        print("je schrikt hier zo van dat je gelijk je hotel verlaat en een taxi beld en zo snel mogelijk weg wilt")
                        print("er komt na 10 minuten een taxi")
                        print("je stapt in en vraagt of hij je naar het vliegveld kan brengen")
                        print("je ziet dat de taxi chauffeur beetje verdacht lijkt")
                        print("je ziet dat hij je elke keer aan kijkt in de spiegel")
                        print("je vind het zo verdacht dat je kan kiezen of je stapt nu uit en loopt verder of je blijft zitten")
                        print("antwoord met stap uit of blijven zitten")
                        
                        keuze20 = input()

                        if keuze20 == 'stap uit':
                            print("je stapt nu uit de auto en betaald de taxi chauffeur")
                            print("je loopt verder naar het vliegveld")
                            print("de taxi rijd snel door")
                            print("je bent ergens beland en je weet niet waar je bent")
                            print("je begint met lopen")
                            print("tijdens dat je loopt krijg je een bericht van het anonieme nummer")
                            print("in het bericht staat een foto")
                            print("de foto is van jou die loopt")
                            print("je kijkt om je heen of je iemand ziet, maar je ziet niemand")
                            print("je begint sneller te lopen")
                            print("er komt een busje langs rijden en stopt voor je neus")
                            print("er stappen 4 mannen uit die op je af komen rennen")
                            print("je wilt weg rennen maar je struikeld en word gepakt door de mannen")
                            print("je word megenomen naar het busje")
                            print("je krijgt een zak over je hoofd en een koptelefoon op")
                            print("je ziet en hoort niks")
                            print("je voelt dat het busje stop en je word het busje uitgetrokken")
                            print("de koptelefoon gaat en en de zak gaat ook van je hoofd")
                            print("je ziet dat je midden in een bos zit")
                            print("de mannen praten in een vreemde taal")
                            print("een van de mannen pakt een wapen en richt het op je")
                            print("hier word youseff om het leven gebracht")
                            print("dankjewel voor het spelen van mijn spel")
                            antwoord11 = input()

                        elif keuze20 == 'blijven zitten':
                            print("je blijft zitten en rijd door")
                            print("na een tijdje zie een bord waar opstaat vliegveld")
                            print("je ziet dat de taxi chauffeur de afslag mist en je vraagt waarom hij niet naar het vliegveld gaat")
                            print("de man begint tegen heb te schreeuwen")
                            print("je vraagt of hij de auto nu stil kan zetten")
                            print("de man versneld de auto naar 150km/h")
                            print("je wilt dat de auto stopt dus je doet je riem af en klimt naar voren en probeert de auto te stoppen")
                            print("je kan kiezen neem je het stuur over of trek je aan de handrem")
                            print("antwoord met sturen of handrem")

                            keuze21 = input()

                            if keuze21 == 'sturen':
                                print("je trekt aan het stuur waardoor de auto een kwartslag draaid")
                                print("de auto draaid een kwartslag en begint over de kop te slaan")
                                print("doordat de auto op een hoge snelheid ging heeft youseff de crash niet overleefd")
                                print("dankjewel voor het spelen van mijn spel")
                                antwoord12 = input()

                            elif keuze21 == 'handrem':
                                print("je trekt aan de handrem en de wielen slippen")
                                print("de man draaid aan zijn stuur")
                                print("de auto draaid een kwartslag en begint over de kop te slaan")
                                print("doordat de auto op een hoge snelheid ging heeft youseff de crash niet overleefd")
                                print("dankjewel voor het spelen van mijn spel")
                                antwoord13 = input()

                    elif keuze5 == 'iran':
                        print("je heb een hotel gevonden in iran waar je de komende week kan verblijven")
                        print("je krijgt na 3 dagen weer een bericht van het anonieme nummer, ze weten weer dat je bent gevlucht. ze weten dat je in een hotel in Iran verblijft.")
                        print("je kiest er voor om weer te vluchten, je kan naar Iraq of naar Europa vluchten")
                        print("antwoord met Iraq of Europa.")

                        keuze6 = input()

                        if keuze6 == 'Iraq':
                            print("je heb er voor gekozen om naar Iraq te vluchten")
                            print("je kan geen verblijf daar vinden, er is in Iraq veel oorlog dus hotels zijn gesloten.")
                            print("je kiest er voor om door de stad te blijven lopen.")
                            print("je heb een foute keuze gemaakt het is in Iraq te gevaarlijk om te verblijven Youseff is hier omgekomen tijdens een bombardement")
                            print("dankjewel voor het spelen van mijn spel.")
                            antwoord14 = input()

                        elif keuze6 == 'Europa':
                            print("Je wilt vluchten anar Europa")
                            print("een vriend van jou kent een smokkelaar die je mee kan nemen naar Europa.")
                            print("hij vraagt 10 000 euro om je te helpen naar Engeland.")
                            print("betaal je de smokkelaar of blijf je in Iran")
                            print("antwoord met betalen of blijven")

                            keuze7 = input()

                            if keuze7 == 'betalen':
                                print("je betaald de smokkelaar 10 000 euro om je mee te nemen naar Engeland.")
                                print("je komt in contact met de smokkelaar en spreekt af in Iran")
                                print("hij komt je ophalen met een zwart busje met geblindeerde ramen")
                                print("je moet al je contact middelen inlever zoals je telefoon")
                                print("de smokkelaar neemt ook je horloge af")
                                print("elke tussen stop is niet te achterhalen waar je bent")
                                print("door de geblindeerde ramen heb je geen idee waar je  bent en hoelaat het is")
                                print("er is een tussen stop in Turkijë bij de vliegveld van Istanbull.")
                                print("bij de vliegveld van Istanbull stappen er 2 andere vluchtenlingen in die ook naar Europa gaan")
                                print("je bent al 2 maanden onderweg naar Engeland")
                                print("je komt aan in een stad. je heb geen idee waar je bent of hoelaat het is.")
                                print("de smokkelaar zecht dat hij wat eten haald voor jullie en dat ze even de benen kunnen strekken")
                                print("je wacht al een uur en de smokkelaar is nog niet terug, je vraagd aan de mensen op straat waar je bent.")
                                print("iemand verteld dat je in Amsterdam bent.")
                                print("je staat om de hoek van het politie bureau")
                                print("je gaat naar de politie en verteld je verhaal")
                                print("de agent met wie je heb gepraat gaat je helpen")
                                print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                                print("je kan nu gaan kiezen of je in Nederland wilt blijven?")
                                print("antwoord met blijven of anderland")

                                keuze8 = input()
                                
                                if keuze8 == 'blijven':
                                    print("je blijft in Nederland en haalt je inburgering en je krijgt een uitkering en je kan werk gaan zoeken.")
                                    print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar nederland krijgen")
                                    print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar nederland")
                                    print("je vrouw haalt ook de inburgering en gaat ook werken")
                                    print("je kinderene gaan hier naar school")
                                    print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                                    print("dankje wel voor het spelen van mijn spel")
                                    antwoord15 = input()

                                elif keuze8 == 'anderland':
                                    print("je kiest er voor om naar een ander land te gaan") 
                                    print("naar welk land wil je gaan: België of Duitsland")
                                    print("antwoord met België of Duitsland")

                                    keuze9 = input()

                                    if keuze9 == 'Duitsland':
                                        print()
                                    elif keuze9 == 'België':
                                        print("je gaat naar belgie en komt aan in antwerpen")
                                        print("je gaat naar een politie bureau en vraagt of iemand je kan helpen")
                                        print("de agent met wie je heb gepraat gaat je helpen")
                                        print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                                        print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar België krijgen")
                                        print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar België")
                                        print("je vrouw haalt ook de inburgering en gaat ook werken")
                                        print("je kinderene gaan hier naar school")
                                        print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                                        print("dankje wel voor het spelen van mijn spel")
                                        antwoord16 = input()


                            elif keuze7 == 'blijven':
                                print("je blijft in Iran")
                                print("na een week moet je uit het hotel en heb je geen onderdak meer")
                                print("er is een week voorbij en je moet het hotel verlaten")
                                print("je neemt een taxi meer richting de grens van iran en afganistan.")
                                print("je komt aan op de grens van afganistan en je wilt weer je eigen land in")
                                print("je komt terug in je eigen land. toen je de grens over ging kreeg je gelijk een bericht weer van het anonieme nummer")
                                print("in het bericht staat: het is een foute keuze dat je bent terug gekomen")
                                print("je loopt naar de supermarkt in de achterbuurd")
                                print("voor de supermarkt zie je een groepje mannen die lang naar jou staren")
                                print("je kan kiezen om de supermarkt in te gaan of weg gaan van de supermakrt")
                                print("antwoord met weg of binnen")

                                keuze10 = input()

                                if keuze10 == 'binnen': 
                                    print("je gaat de supermarkt in en haalt wat te eten en drinken voor je zelf")
                                    print("je loopt de supermarkt uit en de groep is er nog steeds")
                                    print("je loopt op de stoep en de groep loopt snel achter je aan")
                                    print("je begint sneller te lopen en begint te rennen")
                                    print("de groep begint achter je aan te rennen")
                                    print("je rent een steeg in maar die is dood lopend")
                                    print("de groep van mannen staan voor je, je vraagt aan ze of je ze kan helpen")
                                    print("zei antwoorden: je had nooit terug moeten komen")
                                    print("ze beginnen je te slaan en te schoppen")
                                    print("ze verwonden je zo erg dat je het niet overleefd en overlijd in de steeg")
                                    print("je heb het niet overleefd je heb de verkeerde keuze gemaakt.")
                                    print("dankje wel voor het spelen van mijn spel")
                                    antwoord17 = input()

                                elif keuze10 == 'weg':
                                    print("je loopt op de stoep en de groep loopt snel achter je aan")
                                    print("je begint sneller te lopen en begint te rennen")
                                    print("de groep begint achter je aan te rennen")
                                    print("je rent een steeg in maar die is dood lopend")
                                    print("de groep van mannen staan voor je, je vraagt aan ze of je ze kan helpen")
                                    print("zei antwoorden: je had nooit terug moeten komen")
                                    print("ze beginnen je te slaan en te schoppen")
                                    print("ze verwonden je zo erg dat je het niet overleefd en overlijd in de steeg")
                                    print("je heb het niet overleefd je heb de verkeerde keuze gemaakt.")
                                    print("dankje wel voor het spelen van mijn spel")
                                    antwoord18 = input()

                                
elif keuze == 'beantwoorden': 
    print("je wilt het bericht beantwoorden maar het is een anoniem nummer dus je kan het niet beantwoorden.")
    print("je krijgt een bericht dat als je nu niet stopt met werken voor de overheid dat je word vermoord")
    print("je word zo erg bedreigd dat je van plan bent om te vluchten.")
    print("je beld een goede vriend van je of je bij hem even kan verblijven.")
    print("hij neemt op en je verteld wat er is gebeurd en hij begrijpt het en je mag van hem overnachten in zijn huis.")
    print("je verblijft nu al een week bij de vriend. je krijgt weer een bericht van het anonieme nummer.")
    print("ze weten dat je overnacht bij de vriend van je in de hoofdstad van Afganistan.")
    print("je kiest er voor om weer te vluchten, je twijveld om naar een anderland te vluchen of in Afganistan blijven")
    print("antwoord met vluchten of blijven.")
    
    keuze15 = input()
    if keuze15 == 'vluchten':
        print("je wilt vluchten naar een anderland")
        print("je beld een vriend en vraagt of hij je kan helpen")
        print("hij kent een smokkelaar")
        print("hij geeft je het nummer van de smokkelaar")
        print("je stuurt een bericht naar de smokkelaar en vraagt de prijs en waar hij heen gaat")
        print("hij antwoord met voor 10 000 euro breng ik je naar Engeland")
        print("hier moet je een keuze maken ga je betalen of niet")
        print("antwoord met betalen of niet")

        keuze17 = input()
        if keuze17 == 'betalen':
            print("je betaald de smokkelaar 10 000 euro om je mee te nemen naar Engeland.")
            print("je komt in contact met de smokkelaar en spreekt af in Iran")
            print("hij komt je ophalen met een zwart busje met geblindeerde ramen")
            print("je moet al je contact middelen inlever zoals je telefoon")
            print("de smokkelaar neemt ook je horloge af")
            print("elke tussen stop is niet te achterhalen waar je bent")
            print("door de geblindeerde ramen heb je geen idee waar je  bent en hoelaat het is")
            print("er is een tussen stop in Turkijë bij de vliegveld van Istanbull.")
            print("bij de vliegveld van Istanbull stappen er 2 andere vluchtenlingen in die ook naar Europa gaan")
            print("je bent al 2 maanden onderweg naar Engeland")
            print("je komt aan in een stad. je heb geen idee waar je bent of hoelaat het is.")
            print("de smokkelaar zecht dat hij wat eten haald voor jullie en dat ze even de benen kunnen strekken")
            print("je wacht al een uur en de smokkelaar is nog niet terug, je vraagd aan de mensen op straat waar je bent.")
            print("iemand verteld dat je in Amsterdam bent.")
            print("je staat om de hoek van het politie bureau")
            print("je gaat naar de politie en verteld je verhaal")
            print("de agent met wie je heb gepraat gaat je helpen")
            print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
            print("je kan nu gaan kiezen of je in Nederland wilt blijven?")
            print("antwoord met blijven of anderland")

            keuze26 = input()
                               
            if keuze26 == 'blijven':
                print("je blijft in Nederland en haalt je inburgering en je krijgt een uitkering en je kan werk gaan zoeken.")
                print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar nederland krijgen")
                print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar nederland")
                print("je vrouw haalt ook de inburgering en gaat ook werken")
                print("je kinderene gaan hier naar school")
                print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                print("dankje wel voor het spelen van mijn spel")
                antwoord19 = input()

            elif keuze26 == 'anderland':
                print("je wilt naar een anderland")
                print("naar welk land wil je gaan: België of Duitsland")

                keuze25 = input()

                if keuze25 == 'Duitsland':
                    print("je gaat naar Duitsland en komt aan in Berlijn")
                    print("je gaat naar een politie bureau en vraagt of iemand je kan helpen")
                    print("de agent met wie je heb gepraat gaat je helpen")
                    print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                    print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar Duitsland krijgen")
                    print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar Duitsland")
                    print("je vrouw haalt ook de inburgering en gaat ook werken")
                    print("je kinderen gaan hier naar school")
                    print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                    print("dankje wel voor het spelen van mijn spel")
                    antwoord20 = input()

                elif keuze25 == 'België':
                    print("je gaat naar belgie en komt aan in antwerpen")
                    print("je gaat naar een politie bureau en vraagt of iemand je kan helpen")
                    print("de agent met wie je heb gepraat gaat je helpen")
                    print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                    print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar België krijgen")
                    print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar België")
                    print("je vrouw haalt ook de inburgering en gaat ook werken")
                    print("je kinderene gaan hier naar school")
                    print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                    print("dankje wel voor het spelen van mijn spel")
                    antwoord21 = input()

        elif keuze17 == 'niet':
            print("je blijft in afganistan")
            print("na een week moet je uit het hotel en heb je geen onderdak meer")
            print("er is een week voorbij en je moet het hotel verlaten")
            print("je neemt een taxi meer richting de grens van iran en afganistan.")
            print("je komt aan op de grens van afganistan en je wilt weer je eigen land in")
            print("je komt terug in je eigen land. toen je de grens over ging kreeg je gelijk een bericht weer van het anonieme nummer")
            print("in het bericht staat: het is een foute keuze dat je bent terug gekomen")
            print("je loopt naar de supermarkt in de achterbuurd")
            print("voor de supermarkt zie je een groepje mannen die lang naar jou staren")
            print("je kan kiezen om de supermarkt in te gaan of weg gaan van de supermakrt")
            print("antwoord met weg of binnen")

            keuze26 = input()

            if keuze26 == 'binnen': 
                print("je gaat de supermarkt in en haalt wat te eten en drinken voor je zelf")
                print("je loopt de supermarkt uit en de groep is er nog steeds")
                print("je loopt op de stoep en de groep loopt snel achter je aan")
                print("je begint sneller te lopen en begint te rennen")
                print("de groep begint achter je aan te rennen")
                print("je rent een steeg in maar die is dood lopend")
                print("de groep van mannen staan voor je, je vraagt aan ze of je ze kan helpen")
                print("zei antwoorden: je had nooit terug moeten komen")
                print("ze beginnen je te slaan en te schoppen")
                print("ze verwonden je zo erg dat je het niet overleefd en overlijd in de steeg")
                print("je heb het niet overleefd je heb de verkeerde keuze gemaakt.")
                print("dankje wel voor het spelen van mijn spel")
                antwoord41 = input()
                

            elif keuze26 == 'weg':
                print("je loopt op de stoep en de groep loopt snel achter je aan")
                print("je begint sneller te lopen en begint te rennen")
                print("de groep begint achter je aan te rennen")
                print("je rent een steeg in maar die is dood lopend")
                print("de groep van mannen staan voor je, je vraagt aan ze of je ze kan helpen")
                print("zei antwoorden: je had nooit terug moeten komen")
                print("ze beginnen je te slaan en te schoppen")
                print("ze verwonden je zo erg dat je het niet overleefd en overlijd in de steeg")
                print("je heb het niet overleefd je heb de verkeerde keuze gemaakt.")
                print("dankje wel voor het spelen van mijn spel")
                antwoord31 = input()


    elif keuze15 == 'blijven':
        print("je blijft in Afganistan")
        print("je krijgt nog meer berichten van het anonieme nummer met daarin doodsbedeigingen")
        print("je kiest er toch voor om te vluchten")
        print("je beld je oom die woond in iran")
        print("je vraagt hem of je een paar dagen bij hem kan overnachten, hij vind alles prima")
        print("je bent aangekomen bij je oom en kan daar een paar dagen overnachten")
        print("je wilt de hond van je oom uitlaten")
        print("print je bent aan het lopen met de hond van je oom en krijgt een bericht met een foto")
        print("in het bericht staat een foto van jou met de hond met de tekst: je bent nergens veilig")
        print("je kijkt om je heen maar ziet niemand")
        print("je loopt al een tijdje met de hond en bent van plan terug te gaan")
        print("onderweg kom je een groep met mannen tegen")
        print("het valt je op dat ze je lang aanstaren")
        print("je negeerd het maar en loopt door")
        print("je kijkt achter je en ziet dat de groep je achtervolgd")
        print("je begint te rennen")
        print("je komt terug bij je oom en doet alle ramen en duren opslot")
        print("je maakt je oom wakker en verteld wat er allemaal gebeurd")
        print("je wilt weer gaan vluchten want je wilt je familie niet in gevaar brengen")
        print("je beld een vriend of hij je kan helpen")
        print("hij kent een smokkelaar en geeft hem zijn nummer")
        print("de smokkelaar vraagt 10 000 euro ")
        print("ga je hem betalen of niet?")
        print("antwoord met betalen of niet")

        keuze16 = input()
        if keuze16 == 'betalen':
            print("je betaald de smokkelaar 10 000 euro om je mee te nemen naar Engeland.")
            print("je komt in contact met de smokkelaar en spreekt af in Iran")
            print("hij komt je ophalen met een zwart busje met geblindeerde ramen")
            print("je moet al je contact middelen inlever zoals je telefoon")
            print("de smokkelaar neemt ook je horloge af")
            print("elke tussen stop is niet te achterhalen waar je bent")
            print("door de geblindeerde ramen heb je geen idee waar je  bent en hoelaat het is")
            print("er is een tussen stop in Turkijë bij de vliegveld van Istanbull.")
            print("bij de vliegveld van Istanbull stappen er 2 andere vluchtenlingen in die ook naar Europa gaan")
            print("je bent al 2 maanden onderweg naar Engeland")
            print("je komt aan in een stad. je heb geen idee waar je bent of hoelaat het is.")
            print("de smokkelaar zecht dat hij wat eten haald voor jullie en dat ze even de benen kunnen strekken")
            print("je wacht al een uur en de smokkelaar is nog niet terug, je vraagd aan de mensen op straat waar je bent.")
            print("iemand verteld dat je in Amsterdam bent.")
            print("je staat om de hoek van het politie bureau")
            print("je gaat naar de politie en verteld je verhaal")
            print("de agent met wie je heb gepraat gaat je helpen")
            print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
            print("je kan nu gaan kiezen of je in Nederland wilt blijven?")
            print("antwoord met blijven of anderland")

            keuze23 = input()
                               
            if keuze23 == 'blijven':
                print("je blijft in Nederland en haalt je inburgering en je krijgt een uitkering en je kan werk gaan zoeken.")
                print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar nederland krijgen")
                print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar nederland")
                print("je vrouw haalt ook de inburgering en gaat ook werken")
                print("je kinderene gaan hier naar school")
                print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                print("dankje wel voor het spelen van mijn spel")
                antwoord51 = input()

            elif keuze23 == 'anderland':
                print("je wilt naar een anderland")
                print("naar welk land wil je gaan: België of Duitsland")

                keuze24 = input()

                if keuze24 == 'Duitsland':
                    print("je gaat naar Duitsland en komt aan in Berlijn")
                    print("je gaat naar een politie bureau en vraagt of iemand je kan helpen")
                    print("de agent met wie je heb gepraat gaat je helpen")
                    print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                    print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar Duitsland krijgen")
                    print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar Duitsland")
                    print("je vrouw haalt ook de inburgering en gaat ook werken")
                    print("je kinderen gaan hier naar school")
                    print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                    print("dankje wel voor het spelen van mijn spel")
                    antwoord5671 = input()

                elif keuze24 == 'België':
                    print("je gaat naar belgie en komt aan in antwerpen")
                    print("je gaat naar een politie bureau en vraagt of iemand je kan helpen")
                    print("de agent met wie je heb gepraat gaat je helpen")
                    print("je krijgt van hem een uitleg van hoe je hier kan blijven en hoe je moet inburgeren.")
                    print("nadat je hier al een tijdje woont en al werk heb wil je je vrouw en kinderen ook naar België krijgen")
                    print("je vraagt of dat mogelijk is, en het is mogelijk, je vrouw en kinderen komen ook naar België")
                    print("je vrouw haalt ook de inburgering en gaat ook werken")
                    print("je kinderene gaan hier naar school")
                    print("je heb het goede pad gekozen het was zwaar maar je heb nu wel een veilig leven.")
                    print("dankje wel voor het spelen van mijn spel")
                    antwoord1231 = input()

        elif keuze15 == 'niet':
            print("je blijft in Afganistan")
            print("na een week moet je uit het hotel en heb je geen onderdak meer")
            print("er is een week voorbij en je moet het hotel verlaten")
            print("je neemt een taxi meer richting de grens van iran en afganistan.")
            print("je komt aan op de grens van afganistan en je wilt weer je eigen land in")
            print("je komt terug in je eigen land. toen je de grens over ging kreeg je gelijk een bericht weer van het anonieme nummer")
            print("in het bericht staat: het is een foute keuze dat je bent terug gekomen")
            print("je loopt naar de supermarkt in de achterbuurd")
            print("voor de supermarkt zie je een groepje mannen die lang naar jou staren")
            print("je kan kiezen om de supermarkt in te gaan of weg gaan van de supermakrt")
            print("antwoord met weg of binnen")

            keuze30 = input()

            if keuze30 == 'binnen': 
                print("je gaat de supermarkt in en haalt wat te eten en drinken voor je zelf")
                print("je loopt de supermarkt uit en de groep is er nog steeds")
                print("je loopt op de stoep en de groep loopt snel achter je aan")
                print("je begint sneller te lopen en begint te rennen")
                print("de groep begint achter je aan te rennen")
                print("je rent een steeg in maar die is dood lopend")
                print("de groep van mannen staan voor je, je vraagt aan ze of je ze kan helpen")
                print("zei antwoorden: je had nooit terug moeten komen")
                print("ze beginnen je te slaan en te schoppen")
                print("ze verwonden je zo erg dat je het niet overleefd en overlijd in de steeg")
                print("je heb het niet overleefd je heb de verkeerde keuze gemaakt.")
                print("dankje wel voor het spelen van mijn spel")
                antwoord7891 = input()

            elif keuze30 == 'weg':
                print("je loopt op de stoep en de groep loopt snel achter je aan")
                print("je begint sneller te lopen en begint te rennen")
                print("de groep begint achter je aan te rennen")
                print("je rent een steeg in maar die is dood lopend")
                print("de groep van mannen staan voor je, je vraagt aan ze of je ze kan helpen")
                print("zei antwoorden: je had nooit terug moeten komen")
                print("ze beginnen je te slaan en te schoppen")
                print("ze verwonden je zo erg dat je het niet overleefd en overlijd in de steeg")
                print("je heb het niet overleefd je heb de verkeerde keuze gemaakt.")
                print("dankje wel voor het spelen van mijn spel")
                antwoord4561 = input()